Conference/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import app.views as app_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', app_views.login, name='login'),
    url(r'^logout/', app_views.logout, name='logout'),
    url(r'^conference/', include('app.urls')),
    url(r'^$', app_views.index, name='main_index'),

]

app/urls.py
from django.conf.urls import url
from . import views


app_name = 'app'
urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^sessions/$', views.SessionList.as_view(), name='session_list'),
    url(r'^sessions/(?P<pk>[0-9]+)/$', views.SessionDetail.as_view(), name='session_detail'),
    url(r'sessions/add/$', views.SessionCreate.as_view(), name='session_add'),
    url(r'^sessions/(?P<pk>[0-9]+)/update/$', views.SessionUpdate.as_view(), name='session_update'),
    url(r'^sessions/(?P<pk>[0-9]+)/delete/$', views.SessionDelete.as_view(), name='session_delete'),



]

app/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Speaker(models.Model):
    name = models.CharField(max_length=40)
    title = models.CharField(max_length=50)
    bio = models.TextField(max_length=1000)
    twitter = models.CharField(max_length=16, blank=True)
    facebook = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.name


class Track(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(max_length=1000)

    def __str__(self):
        return self.title


SESSION_STATUSES = (
    ('a', 'Approved',),
    ('s', 'Submitted',),
    ('r', 'Rejected',),
)


class Session(models.Model):
    title = models.CharField(max_length=40)
    abstract = models.TextField(max_length=2000)
    track = models.ForeignKey(Track)
    speaker = models.ForeignKey(Speaker)
    status = models.CharField(max_length=1, choices=SESSION_STATUSES)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('app:session_detail', kwargs={'pk': self.pk})

app/forms.py
from django.forms import ModelForm
from .models import Session
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class SessionForm(ModelForm):
    class Meta:
        model = Session
        fields = ['title', 'abstract', 'track', 'speaker']

    def __init__(self, *args, **kwargs):
        super(SessionForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-offset-1 col-md-2'
        self.helper.field_class = 'col-md-8'
        self.helper.add_input(Submit('submit', 'submit', css_class='btn btn-success'))
        self.helper._form_method = 'POST'

app/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse_lazy, reverse
from django.contrib import auth
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Session
from .forms import SessionForm
from django.contrib.auth.mixins import LoginRequiredMixin


def index(request):
    return render(request, 'index.html')


def logout(request):
    auth.logout(request)
    return redirect('/conference/')


def login(request):
    if request.method == 'GET':
        return render(request, 'auth/login.html')
    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                auth.login(request, user)
                next = ''
                if 'next' in request.GET:
                    next = request.GET['next']
                if next == None or next == '':
                    next = '/'
                return redirect(next, {'message': 'Logged in!!'})
            else:
                return render(request, 'auth/login.html', {
                    'warning': 'Your account has been disabled'
                })
        else:
            return render(request, 'auth/login.html', {
                'warning': 'Invalid username or password'
            })


# @login_required
# def submit_session(request):
#     return render(request, 'submit_session.html')


class SessionList(ListView):
    model = Session
    template_name = 'app/sessions.html'
    context_object_name = 'sessions'


class SessionDetail(DetailView):
    model = Session
    context_object_name = 'session'
    template_name = 'app/session.html'


class SessionCreate(LoginRequiredMixin, CreateView):
    model = Session
    form_class = SessionForm


class SessionUpdate(LoginRequiredMixin, UpdateView):
    model = Session
    form_class = SessionForm


class SessionDelete(LoginRequiredMixin, DeleteView):
    model = Session
    success_url = reverse_lazy('app:session_list')

app/templates/about.html
{% extends 'layout.html' %}

{% block content %}
<p> {{requestMethod}}</p>
{% endblock %}

app/templates/app/session.html
{% extends 'layout.html' %}

{% block content %}


<div class="row">
    <div class="col-md-3">
        <strong>Title: </strong>
    </div>
    <div class="col-md-9">{{ session.title}}</div>
</div>

<div class="row">
    <div class="col-md-3">
        <strong>Speaker: </strong>
    </div>
    <div class="col-md-9">{{ session.speaker}}</div>
</div>

<div class="row">
    <div class="col-md-3">
        <strong>abstract: </strong>
    </div>
    <div class="col-md-9">{{ session.abstract}}</div>
</div>

<div class="row">
    <div class="col-md-3">
        <strong>Track: </strong>
    </div>
    <div class="col-md-9">{{ session.track}}</div>
</div>

<div class="row">
    <p>
        <div class="col-md-3 col-md-offset-3">

             <a href="{% url 'app:session_list' %}"> <<< return to list</a>

        </div>
    </p>

</div>
{% endblock %}

app/templates/app/session_confirm_delete.html
{% extends 'layout.html' %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
    <p>Are you sure you want to delete the item <b>'{{session.title}}'</b>? </p>
    <input class="btn btn-primary" type="submit" value="Confirm"/>
    <button onclick="window.history.back();" class="btn btn-default" type="button">Cancel</button>
</form>

{% endblock %}

app/templates/app/session_form.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="POST">
        {% csrf_token %}

        {% crispy form %}
    </form>

{% endblock %}

app/templates/app/sessions.html
{% extends 'layout.html' %}
{% load staticfiles %}

{% block styles %}
    <link  href="{% static 'app/css/styles.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

{% if user.is_authenticated %}
    <div class="row">
         <div id="session-add-btn">
                <a href="{% url 'app:session_add' %}">
                    <button type="button" class="btn btn-primary btn-lg">
                      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    </button>
                </a>
         </div>
    </div>
{% endif %}

    <h2>Available Sessions</h2>

    {% for session in sessions %}
        <div class="col-md-8">
            <a href="{% url 'app:session_detail' session.pk %}">>
                   {{session.title}}

            </a>
        </div>
        <div class="col-md-2">
            <a href="{% url 'app:session_update' session.pk %}">
                <button type="button" class="btn btn-default btn-lg">
                  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </button>
            </a>
        </div>
        <div class="col-md-2">
            <a href="{% url 'app:session_delete' session.pk %}">
                <button type="button" class="btn btn-default btn-lg">
                  <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                </button>
            </a>
        </div>
    {% endfor %}
{% endblock %}

app/templates/index.html
{% extends 'layout.html' %}
{% block content %}
{% if message %}
    <div class="alert alert-success" role="alert">
      <strong>{{message}}</strong>
    </div>
{% endif %}

{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
{% load staticfiles %}
{% include 'partials/_header.html'%}
{% include 'partials/_navbar.html'%}

    <div class="container">
    <div class="jumbotron ">
       <h2> Welcome to adventure works!</h2>
    </div>
   
    
    <div class="row">
        <div class="col-md-12">
            {% block content %}
            {% endblock %}
        </div>
     </div>
    </div><!-- /.container -->

{% include 'partials/_footer.html' %}

app/templates/partials/_footer.html
 {% load staticfiles %}
 <script src="{% static 'app/js/jquery.1.11.1.js' %}"></script>
<script src="{% static 'app/js/bootstrap.min.js' %}"></script>
{% block scripts%}
{% endblock %}
  </body>
</html>

app/templates/partials/_header.html
<html>
  <head>
      <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="Adventure Works Conference">
    <meta name="author" content="Isaac-IJ">
    <link rel="icon" href="../../favicon.ico">

    <title>Adventure Works Conference</title>
    {% load staticfiles %}
    <link href="{% static 'app/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'app/css/starter-template.css' %}" rel="stylesheet">

    {% block styles %}
    {% endblock %}
 </head>

    <body>

app/templates/partials/_navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'app:index' %}">Adventure Works Conference</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'app:session_list' %}">Sessions</a></li>

            {% if user.is_staff %}
              <li><a href="/admin">Administration</a></li>
            {% endif %}

            {% if user.is_authenticated %}
              <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
              <li><a href="{% url 'login' %}">Login</a></li>
            {% endif %}


          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/templates/submit_session.html
{% extends 'layout.html' %}
{% block content %}

<h2>Submit Session</h2>

{% endblock %}